### PR TITLE
WaveBot: example script readability and comments

### PR DESCRIPTION
**Pull request by ryancoe**
## Description
Minor changes to improve the readability of the WaveBot example scripts and to add comments where appropriate to make the higher level meanings of steps within the code more clear.

## Checklist:

- [x] Added the results of running the test suite (in pdf form)

### CODE REVIEW

**Comment by ryancoe** [comment]
All tests pass: [test_results.pdf](https://github.com/SNL-WaterPower/WecOptTool/files/5285490/test_results.pdf)

**Comment by ryancoe** [comment]
@H0R5E - If you find this ready for merge, please go ahead and execute.

**Comment by H0R5E** [comment]
Still good without the PCT.

[test_results_no_pct.pdf](https://github.com/SNL-WaterPower/WecOptTool/files/5293262/test_results_no_pct.pdf)

**Review by H0R5E — APPROVED** [review]
So, the only thing I would say is that "Monte-carlo" is a bit of a stretch to describe the simulation of the pre-selected radii in case B, given there is no randomness to the selection of the values.

**Comment by ryancoe** [comment]
Monte-Carlo: yes, good point... dealing with a deterministic system in this case it doesn't seem that random sampling would add anything... probably best to leave it at "brute force" though

**Pull request merged**
