### PR TITLE
update tutorial 1

### PR DESCRIPTION
**Pull request by ryancoe**
## Description
- add photo of WaveBot
- move up impedance plot

## Type of PR
- [ ] Bug fix
- [ ] Major change
- [ ] New feature

## Checklist for PR
- [x] Authors read the [contribution guidelines](https://github.com/SNL-WaterPower/WecOptTool/blob/main/.github/CONTRIBUTING.md)
- [x] The pull request is from an issue branch (not main) on your fork to the [main branch in WecOptTool](https://github.com/SNL-WaterPower/WecOptTool). 
- [x] The authors have given the admins edit access
- [x] All changes adhere to the style guide including PEP8, Docstrings, and Type Hints.
- [ ] Added note in [Changelog](https://github.com/SNL-WaterPower/WecOptTool/blob/main/CHANGES.md)
- [ ] Modified the documentation if applicable
- [ ] Modified or added a new test
- [x] All tests pass
- [x] Documentation builds
- [ ] [Reference or close any relevant issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

## Additional details
Include any relevant context and describe any validation and verification efforts.

### CODE REVIEW

**Comment by ryancoe** [comment]
@cmichelenstrofer - It looks like you did something fancy to store the image online for `tutorial_2_wavebot_optimization.ipynb`: https://github.com/SNL-WaterPower/WecOptTool/blob/6bd7c8f8561a9bfdaf2b0b39f3b6921a1b1d8562/examples/tutorial_2_wavebot_optimization.ipynb?short_path=bbb3285#L21

Do you want to do the same thing for the photo in this case?

WaveBotPhoto

**Comment by ryancoe** [comment]
Would be nice to complete #37 before finishing this one.

**Comment by cmichelenstrofer** [comment]
@ryancoe Embedding a figure into a notebook does not work too well. You would have to push the figure too and have it in the same directory. The best solution is to use URL for an image online. What I did was create a flickr account and upload that image. In the notebook I simply wrote 
```
![Device Diagram](https://live.staticflickr.com/65535/51751577441_515afec334_z.jpg)
```

I will do this with the new image. Sandia and DOE both have a flickr account. We could also use an image from there.

**Comment by cmichelenstrofer** [comment]
@ryancoe I added the continuous time plotting but the PTO Power is not matching. There is a bug. Can you take a quick look?

**Comment by ryancoe** [comment]
**continuous time plotting:** I don't see anything immediately... I might need to look at it with you in order to have much luck

**Pull request merged**
