### PR TITLE
Conda install and conda-forge CI

### PR DESCRIPTION
**Pull request by michaelcdevin**
## Description
Add a conda build to [`conda-forge`](https://conda-forge.org) to enable a conda install of `wecopttool` to make the install process cleaner and more straightforward than pip. The `conda-forge` build should have continuous integration so it is automatically updated on each new commit to the `main` branch.

## Type of PR
- [ ] Bug fix
- [ ] Major change
- [x] New feature
- [ ] Other

### New functionality
- [x] Conda recipe created and added to `./conda` subdirectory
- [x] Package builds and installs locally
- [ ] Add package to [conda-forge](https://conda-forge.org/#add_recipe)
- [ ] Package installs successfully through conda via conda-forge on:
  - [ ] Windows
  - [ ] MacOS
  - [ ] Linux
- [ ] README install instructions updated
- [ ] [Release instructions](https://github.com/SNL-WaterPower/WecOptTool/blob/main/.github/RELEASING.md) updated
- [ ] Continuous integration: conda-forge build updates automatically on a new push to `main`
### General
- [x] Authors read the [contribution guidelines](https://github.com/SNL-WaterPower/WecOptTool/blob/main/.github/CONTRIBUTING.md)
- [x] The pull request is from an issue branch (not main) on your fork to the [main branch in WecOptTool](https://github.com/SNL-WaterPower/WecOptTool).
- [ ] The authors have given the admins edit access
- [ ] All changes adhere to the style guide including PEP8, Docstrings, and Type Hints.
- [ ] Added note in [Changelog](https://github.com/SNL-WaterPower/WecOptTool/blob/main/CHANGES.md)
- [ ] Modified the documentation if applicable
- [ ] Modified or added a new test
- [ ] All tests pass
- [ ] Documentation builds
- [ ] [Reference or close any relevant issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

### CODE REVIEW

**Comment by michaelcdevin** [comment]
A complicating factor to this is that `pygmsh` does not have a conda installation, only PyPI. There appears to be a way to build a conda package from a wheel file, which is the solution I am going with for the time being (still a work in progress, though). This shouldn't cause dependency issues since the only non-standard libraries in `pygmsh` are `gmsh` and `numpy`, both of which have conda installs. However, we should keep this in mind in case `pygmsh` ever changes.

**Comment by michaelcdevin** [comment]
> Who develops pygmsh? is it on GitHub? You can always create an issue (check first if one already exists), asking them to create a conda package. Not a solution for right now, more long term. But it is good to let them know we use their tool and wish they had a conda package.

@nschloe is the lead developer on it. I was planning on creating an issue on the GitHub repo about this. Theoretically this should be very straightforward so this may be something we could even do for them, but I'll definitely get our own conda build working first for v2.1

**Comment by cmichelenstrofer** [comment]
@michaelcdevin  when this is working, can you add a short section to [release instructions](https://github.com/SNL-WaterPower/WecOptTool/blob/main/.github/RELEASING.md) similar to the PyPi section.

**Comment by michaelcdevin** [comment]
> @michaelcdevin when this is working, can you add a short section to [release instructions](https://github.com/SNL-WaterPower/WecOptTool/blob/main/.github/RELEASING.md) similar to the PyPi section.

Will do! Added this to the PR checklist.

**Comment by michaelcdevin** [comment]
Update: conda build is completing *mostly* successfully, but the wheel install for `pygmsh` is still causing hassles. I'm getting the following non-fatal exception during the build:

```
(%PREFIX%) %SRC_DIR%>pip install pygmsh
ERROR: Could not find a version that satisfies the requirement pygmsh (from versions: none)
ERROR: No matching distribution found for pygmsh
```

**Comment by michaelcdevin** [comment]
Conda recipe has been uploaded to `conda-forge/staged-recipes` and submitted a PR, see [here](https://github.com/conda-forge/staged-recipes/pull/21085)

**Comment by cmichelenstrofer** [comment]
Awesome! Anything new on the meshing?

**Comment by michaelcdevin** [comment]
No updates with the meshing at the moment, but I should have time to look at that later this week.

**Comment by cmichelenstrofer** [comment]
Our conda-forge repo (feedstock) is here: https://github.com/conda-forge/wecopttool-feedstock

Thanks @michaelcdevin 💯

**Pull request closed without merging**
