### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by ryancoe**
@cmichelenstrofer has provided a nice template for the documentation pages; I've done some initial work to flush these out, based mostly on [`WecOptTool-MATLAB`](https://github.com/SNL-WaterPower/WecOptTool-MATLAB).

- [x] Basic content
- [x] Automated deployment: https://github.com/marketplace/actions/sphinx-docs-to-github-pages  <- maybe this?
- [x] Update version numbers (in `setup.py`)
- [x] Link to docs from Github (via "About")

### CODE REVIEW

**Comment by ryancoe** [comment]
@cmichelenstrofer - Can you merge in your main branch changes, complete the remaining tasks detailed above, and merge?

**Comment by cmichelenstrofer** [comment]
@ryancoe Whats do you mean by "Link to docs from Github (via "About")"? That's the only missing task.

**Comment by ryancoe** [comment]
Yeah, sorry, wasn't sure how to describe that. You can use the Settings to put a link to the docs here

image

**Review by cmichelenstrofer — APPROVED** [review]
Looks good. Compiles. I merged the latest changes in `main` and fixed some small typos.

**Pull request merged**
