### PR TITLE
Update docs and README for version 1.0

### PR DESCRIPTION
**Pull request by H0R5E**
## Description

* Update the online Setup page to match the README.
* Edit README and docs for MATLAB support policy
* Fix typo in Hydrodynamics class docstring
* Fix line numbers in optimization example

### CODE REVIEW

**Review by ssolson — COMMENTED** [review]
Great job on this Mat! Minor comments below:

`setup.rst` line 48 we need to update the latest current version

`optimization.rst` inconsistent use of "seastate", "sea state", and "sea-state". I think the space is more common.

I think I caught them all but you had a mix of zations and sations. As a US taxpayer-funded project we should use zations.

**Comment by H0R5E** [comment]
Sterling, I was a bit confused because you've made the changes on a branch in your repo, rather than mine.

**Comment by ssolson** [comment]
> Sterling, I was a bit confused because you've made the changes on a branch in your repo, rather than mine.

Yeah I have decided it is very easy to create PRs. Far easier than trying to select and compare multiple commits someone pushed to my open PR and make sure I know exactly what was changed.

**Comment by H0R5E** [comment]
OK, I see. But you didn't create a PR in this case, right?

**Comment by ssolson** [comment]
Apologies. I can't see since you deleted the branch but I guess not! Yes, that would have been confusing!

**Comment by H0R5E** [comment]
I didn't delete your branch.

**Comment by ssolson** [comment]
...I know that. I do not know of a way to see if I had a PR open on your deleted branch.

**Comment by H0R5E** [comment]
The PR would still be on Github, whatever branch you used as the baseline. It would just say that the source branch has been deleted.

**Comment by ssolson** [comment]
I don't know how to see that. I deleted my branch and I believe I did not submit a PR.

**Pull request merged**
