### PR TITLE
x scale logging

### PR DESCRIPTION
**Pull request by ryancoe**
## Description
Update the x scale logging

- control entirely via `logging` configuration (set to `INFO`
- missing commas

## Type of PR
- [x] Bug fix
- [ ] Major change
- [ ] New feature

## Checklist for PR
- [x] Authors read the [contribution guidelines](https://github.com/SNL-WaterPower/WecOptTool/blob/main/.github/CONTRIBUTING.md)
- [x] The pull request is from an issue branch (not main) on your fork to the [main branch in WecOptTool](https://github.com/SNL-WaterPower/WecOptTool). 
- [x] The authors have given the admins edit access
- [x] All changes adhere to the style guide including PEP8, Docstrings, and Type Hints.
- [x] Added note in [Changelog](https://github.com/SNL-WaterPower/WecOptTool/blob/main/CHANGES.md)
- [x] Modified the documentation if applicable
- [ ] Modified or added a new test
- [ ] All tests pass
- [ ] Documentation builds
- [ ] [Reference or close any relevant issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

### CODE REVIEW

**Review by cmichelenstrofer — APPROVED** [review]
Looks good. 

I think this information is good to print, but I don't think we can use it the way we were trying to the other day. The initial `x_wec` and `x_opt` are randomly initialized so they tell us little about their relative magnitudes. What really matters is the relative magnitudes between the optimal solutions for these two. But that is difficult to know.

**Comment by ryancoe** [comment]
I think that since the random initial guess is done by [`np.random.randn`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html), it will always be on the order of 1e1. We need the scaling to make sure that gradients calculated during the solution process are of accurate, which requires that the step size used for the numerical gradient is similar in the different directions. For this reason, I think that the scaling during the solution process makes sense to check.

https://github.com/SNL-WaterPower/WecOptTool/blob/51c3aea47098ab1a7cf6c2a8f9801ff60de5645e/wecopttool/core.py#L657-L662

**Review by cmichelenstrofer — APPROVED** [review]

**Comment by ryancoe** [comment]
@cmichelenstrofer - Can you look quickly at this once more (made a change to the docs).

**Review by cmichelenstrofer — APPROVED** [review]
Compiled the docs in my computer. looks good.

**Pull request merged**
